name: Build MKP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: version
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      - name: Build MKP package
        id: build
        uses: oposs/mkp-builder@v2
        with:
          version: ${{ steps.version.outputs.version }}
      - name: Upload MKP artifact
        uses: actions/upload-artifact@v4
        with:
          name: fortios-fw-mkp
          path: ${{ steps.build.outputs.package-file }}
